### PR TITLE
pug components for portfolio entries

### PR DESCRIPTION
**Pull request by Elia-Sh**
added some pug components, 
will probably add additional features to this fork - 
1. use pug variables for generalization of the components
2. replace `SB_WATCH` behavior to serve static content using: `http-server` node modules ->
  for me this was the simplest solution to prevent automatic open of browser on execution of `npm start` **and** able to see changes to pug files in "real time" while developing pug components,
`browser-sync` misbehaved in this case - files were recompile, but browsers did not load changes properly.

### CODE REVIEW

**Comment by Elia-Sh** [comment]
@davidtmiller , 
please notice the following commits to this fork,
instead of **replacing** `browser-sync` I've added a "static-start" script, 
this keeps the old behavior of `npm start`, 
and adds the new functionality - `npm run start:static` as shown bellow - 
```
$ npm run start:static
... regular output for npm-start ...
... compiling etc ...
.....

[SB_WATCH_SERVER] Starting up http-server, serving dist
[SB_WATCH_SERVER] Available on:
[SB_WATCH_SERVER]   http://127.0.0.1:8080
[SB_WATCH_SERVER]   http://192.168.0.13:8080
[SB_WATCH_SERVER] Hit CTRL-C to stop the server
[SB_WATCH] Loading..................................... READY TO ROLL!
```

This addition of behavior instead of replacement is done in order to keep backward comparability, 
and since removal of `browser-sync` will also affect on the debug script, ie - `npm run start:debug`, and I don't familiar with all the features of  `browser-sync`, so maybe they have indeed something really useful for "debugging", 
but from my point of view - 

1. `http-server` is less convoluted than `browser-sync` 
2. `http-server` is smaller in size - probably also much faster performance wise - but did not test myself, so the performance is more of an assumption
3. `http-server` also showing higher potential when examining the github activity of both projects.

I hope that for simplicity the usage of `browser-sync` will be phased out.

Best regards, 
Elia.

**Comment by Elia-Sh** [comment]
Added 
*  variables for ease of text modifications in pug components
* delayed pug rendering - no need to re-render on every keyboard stoke :)

@davidtmiller  feel free to get in touch for further collaboration :)

**Comment by davidtmiller** [comment]
Hey there @Elia-Sh 

These look pretty sweet! I am going to be doing a round of updates for Bootstrap 4.5 and I will review these changes when I get to the dependency updates for this theme.

**Comment by davidtmiller** [comment]
How exactly was browser sync misbehaving?

**Comment by Elia-Sh** [comment]
I think I've reproduced the re-rendering issue of bug included components - 
@davidtmiller please see the side branch that includes the [commit](https://github.com/Elia-Sh/startbootstrap-freelancer/commit/ebe15d4f215f40be2ad008e3bc85767b6235ad9e),
part of the side [test_browserSync](https://github.com/Elia-Sh/startbootstrap-freelancer/commits/test_browserSync) branch.

In order to reproduce - 

1. Checkout the commit from [test_browserSync](https://github.com/Elia-Sh/startbootstrap-freelancer/commits/test_browserSync) branch.
    OR add you pug component as an "included" component to `src/pug/index.pug`
2. run `npm start` -> to start serving "dist" dir, and watching for file changes
3. make a change in the **included** pug component
4. check if change rendered to the browser
5. if change was re-rendered, try another change, 
after 3-5 changes, browserSync starts to misbehave - and not re-rending the changes.
6. terminate your `npm start`; 
    rerun `npm start`
    -> now the changes to your pug component are rendered as expected,
         **until browserSync misbehaves again** after another couple of changes to the pug component.

Tested on osx and both firefox and chromium present same behavior.

**Pull request closed without merging**
